_target_: transformers.AutoModelForCausalLM.from_pretrained
pretrained_model_name_or_path: "stockmark/gpt-neox-japanese-1.4b"
trust_remote_code: true
device_map: "auto"
load_in_8bit: false
load_in_4bit: false
